### ISSUE TITLE
Add _json attribute to profile

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/passport-oxd#1]
All Passport.js strategies that I know of, attach a `_json` attribute to the profile with the whole profile as received by the external identity provider. 

l think we should do the same to harmonize. Also we use it in Gluu Passport for debugging purposes.

Here is an example of what I mean:
https://github.com/jaredhanson/passport-openidconnect/blob/master/lib/strategy.js#L199

You can see others: passport-tumblr, passport-twitter, etc...

**Comment by ldeveloperl1985** [comment]
@jgomer2001 Yes, but we don't need it because passport-oxd already returning the whole profile(which is return by the external identity provider as it is) in **userInfoResponse**. I can see other libraries modifies the userinfo and return it in profile and separate _json as whole profile which is redundancy of code and it is not really a good way.

```
passport.use(
  new OXDStrategy({...}, (req, accessTokenResponse, userInfoResponse, done) => {
  // userInfoResponse: As it is response send by identity server
  })
);
```

so in-short you can use directly `userInfoResponse` which is already in json formate and no need for extra **_json**.

You will get data in `userInfoResponse` is like below which is return by oxd user-info api. https://gluu.org/docs/oxd/4.0/api/#operations-developers-get-user-info

```
{
            "sub": "248289761001",
            "name": "Jane Doe",
            "given_name": "Jane",
            "family_name": "Doe",
            "preferred_username": "j.doe",
            "email": "janedoe@example.com",
            "picture": "http://example.com/janedoe/me.jpg"
}
```

If you still wanna any change, please let me know.

**Comment by jgomer2001** [comment]
@ldeveloperl1985  Yes, the issue is not about a bug or misbehavior. It works very well as is. My interest is just harmonizing. 

Also in  passport 4.0 we don't treat every strategy differently, it's just a single code which handles all strategies the same way (no `switch`/`ifs` or separate js file for every strat). Ideally we could rely on existence of `_json` for all strategies despite in this case it is sort of redundant.

**Comment by ldeveloperl1985** [comment]
Yes `_json` is redundant. You are already getting same values in `userinforesponse`. I am closing it.
